/*
Generated by Yara-Rules
On 24-01-2018
*/
include "./email/EMAIL_Cryptowall.yar"
include "./email/image.yar"
include "./email/scam.yar"
include "./email/attachment.yar"
include "./email/urls.yar"
include "./email/bank_rule.yar"
include "./email/email_Ukraine_BE_powerattack.yar"
