/*
Generated by Yara-Rules
On 16-01-2020
*/
include "./packers/JJencode.yar"
include "./packers/Javascript_exploit_and_obfuscation.yar"
include "./packers/packer.yar"
include "./packers/packer_compiler_signatures.yar"
include "./packers/peid.yar"
