/*
Generated by Yara-Rules
On 06-02-2018
*/
include "./Packers/JJencode.yar"
include "./Packers/packer.yar"
include "./Packers/peid.yar"
include "./Packers/Javascript_exploit_and_obfuscation.yar"
include "./Packers/packer_compiler_signatures.yar"
