/*
Generated by Yara-Rules
On 14-09-2016
*/
include "./Packers/peid.yar"
include "./Packers/JJencode.yar"
include "./Packers/packer_compiler_signatures.yar"
include "./Packers/packer.yar"
include "./Packers/Javascript_exploit_and_obfuscation.yar"
